#!/usr/bin/env node
/**
 * Leaves only the installers people download in dist/:
 *   OfficeLink-<version>-mac-arm64.dmg, OfficeLink-<version>-mac-x64.dmg,
 *   OfficeLink-Setup-<version>-win-x64.exe
 * Everything else electron-builder writes (unpacked apps, blockmaps, logs,
 * older versions) is regenerated by the next build.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dist = path.join(root, 'dist');
const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const keep = new Set([
  `OfficeLink-${version}-mac-arm64.dmg`,
  `OfficeLink-${version}-mac-x64.dmg`,
  `OfficeLink-Setup-${version}-win-x64.exe`,
]);

if (!fs.existsSync(dist)) process.exit(0);
for (const name of fs.readdirSync(dist)) {
  if (keep.has(name)) continue;
  fs.rmSync(path.join(dist, name), { recursive: true, force: true });
}
const left = fs.readdirSync(dist);
console.log(left.length ? `dist/ now has:\n  ${left.join('\n  ')}` : 'dist/ is empty');
